### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by francescopellegrini** [confluentinc/common#242]
Support for Scala 2.13 was [added to Kafka in 2.4.0](https://github.com/apache/kafka/pull/6989), but Confluent artifacts are [still lacking it](https://docs.confluent.io/5.4.0/installation/versions-interoperability.html#scala).

It would be amazing of you to add it soon, so that third party libraries built in Scala could be released (e.g., embeddedkafka/embedded-kafka-schema-registry#78).

**Comment by francescopellegrini** [comment]
v5.4.1 is still not ready. :(

**Comment by francescopellegrini** [comment]
Given the [upcoming drop of Scala 2.11 support in Kafka 2.5](https://cwiki.apache.org/confluence/display/KAFKA/KIP-531%3A+Drop+support+for+Scala+2.11+in+Kafka+2.5), do you think this could be reconsidered?

**Comment by ewencp** [comment]
It's unlikely we'd add support in a bugfix release like 5.4.1 (it is a *bugfix* release after all...), but we do have 2.13 support on the roadmap. It's a bit more involved to add support across Confluent Platform than just Apache Kafka since it covers a lot more projects and code, but we're looking at it. It may look a bit different from what we've done historically, but I'm guessing will probably serve your needs. Previously, we've both published maven artifacts and packages (e.g. schema registry binaries) with multiple scala versions. It's likely that we'll move to publishing maven artifacts for multiple scala versions so you can link against libraries safely, but publish a single canonical version of services with a single, specific scala version.

**Comment by francescopellegrini** [comment]
Hi, I was able to build a 2.13 version of my library including kafka-avro-serializer and kafka-schema-registry artifacts but excluding transitive Kafka-related dependencies. :)

**Comment by francescopellegrini** [comment]
Closed by #260?
