### ISSUE TITLE
DataException raised in AvroData.toConnectData

### ISSUE THREAD

**Issue by litianxing** [confluentinc/common#30]
when I use confluent to load data from DB2 to HDFS I found something strange ,when there are some NULL value in a table of DB2, It CAN NOT be LOADED successfully,there is a EXCEPTION raised.

**Comment by cricket007** [comment]
Since the exception is with `AvroData`, this issue should probably be closed and moved to https://github.com/confluentinc/schema-registry/issues if still a problem

**Comment by ewencp** [comment]
Yeah, I'm going to close this since it's on a completely unrelated repository.

This is a bit of a tough case in that, with the description provided so far, it's actually hard to tell where the issue lies -- could be in the AvroConverter in the schema-registry repo, but it could also be an issue with a Connector, and it sounds like you are probably using 2 of them (maybe jdbc for DB2 -> Kafka? and then presumably HDFS connector for Kafka -> HDFS). In general, more info provided with the bug report will make it possible to find the problem, so having a full stacktrace would be a good starting point. Even better if there were connector configs or example data and schemas that caused the problem (e.g. is it any `null` value? or just for a specific column type? any other hints as to the source of the problem?).
